services:
    sms_gateway:
        class: EffectiveSolutions\SMSGatewayBundle\SMSGateway\SMSGateway
        arguments: ['@mailer','%server_parameters%']
#        arguments: [@service_id, "plain_value", %parameter%]